# Generated by Django 5.2.7 on 2025-10-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year_of_admission',
            field=models.IntegerField(verbose_name=2025),
        ),
    ]
