# Generated by Django 5.2.7 on 2025-10-20 14:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_year_of_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_id_img',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='The image of the staff ID card', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='matric_number',
            field=models.CharField(blank=True, help_text='The matric number of student', max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_id',
            field=models.CharField(blank=True, help_text='Id of staff', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'doctor'), ('nurse', 'nurse'), ('student', 'student'), ('admin', 'admin')], default='student', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_of_admission',
            field=models.IntegerField(default=2025),
        ),
    ]
