# Generated by Django 5.2.7 on 2025-10-20 16:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_staff_id_img_alter_user_matric_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, help_text='Date user joined.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether the user account is active.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Indicates whether the user has all admin permissions.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='matric_number',
            field=models.CharField(blank=True, help_text='The matric number of the student (optional).', max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="User's profile image.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_id',
            field=models.CharField(blank=True, help_text='The ID of the staff member.', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_id_img',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='The image of the staff ID card.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'doctor'), ('nurse', 'nurse'), ('student', 'student'), ('admin', 'admin')], default='student', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified_staff',
            field=models.BooleanField(default=False, help_text='Whether the staff is verified or not.'),
        ),
    ]
